### ISSUE TITLE
Windows 10 BSOD on boot

### ISSUE THREAD

**Issue by VixiKitsune** [worproject/rpi5-uefi#11]
I've installed Windows 10 build 19045.2965.230505-1139.22h2 to a 128GB Samsung Evo Plus (the newer white V30 version) with WoR imager set to Raspberry Pi 2/3 and then replaced files in the efi partition with the ones from this repo. Upon booting it shows the Windows 10 loading circle on the bios screen then hits a BSOD

I am using the Rasbperry Pi 4 5.1V 3A PSU
I've set usb_max_current_enable= to 0
I have a USB keyboard and a logitech wireless reciever in the USB 2.0 ports.
SD card is U3 V30 which is SDR50 is I'm not mistaken?

Stop code: INACCESSIBLE_BOOT_DEVICE

**Comment by mariobalanica** [comment]
Answered on Discord.

If anyone else runs into this: only Windows 10 is affected; 11 works fine. You may be able to replace the `sdbus` driver on 10, but this version is not supported here anymore.
