### ISSUE TITLE
RPI5 with SSD

### ISSUE THREAD

**Issue by Spuxy** [worproject/rpi5-uefi#6]
Hi first, thanks for ur project, its marvellous repository.
Im worried if i meed the requriments. I have pineberry hat for nvme disk, which is conntected via FPC.
If i want to boot from `uefi` to debian/raspberry os, i need to have it on different disk, then is my `root`/`partitions` etc.. ?
I mean if i need to buy another sd cards for just uefi.

**Comment by mariobalanica** [comment]
PCIe support is now available in the latest build artifact.
